### ISSUE TITLE
Can't add preview image for new templates

### ISSUE THREAD

**Issue by daltonrooney** [spicywebau/craft-content-templates#9]
### Bug Description

New installation of the plugin, no other plugins or modules currently installed. I'm able to create new content templates, but the "Add" button for the preview image seems to be unresponsive. Clicking it has no effect, and no message in the console.

### Expected behaviour

Clicking the "Add" preview image button should open an asset modal, I presume?

### Content Templates version

2.0.1

### Craft CMS version

 5.4.6

**Comment by ttempleton** [comment]
I'm guessing that no preview image menu has appeared because no images were found in your [preview source folder](https://github.com/spicywebau/craft-content-templates/blob/2.0.2/docs/plugin-settings.md#previewsource). I've just released 2.0.2, which removes the add button in that case, and replaces it with an alert about the lack of images found, and a link to the plugin settings so that the preview source folder path can be changed.

Please let me know if 2.0.2 does not resolve your issue, and I'll reopen this.

**Comment by daltonrooney** [comment]
Ah, thanks, I should have read the docs a bit more closely, but your solution does make things more clear!
